pipeline {
    agent any 
    
    stages { 
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    git branch: 'main', url: 'https://github.com/waplak/frontend-react-apps.git'
                }
            }
        }
        stage('Build Docker Image') {
            steps {  
                dir('starting-project') {
                    bat 'docker build -t waplak/react-app:%BUILD_NUMBER% .'
                }
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'credentialsId', variable: 'waplakSecret')]) {
                    script {
                        bat "docker login -u waplak -p %waplakSecret%"
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                bat 'docker push waplak/react-app:%BUILD_NUMBER%'
            }
        }
    }
    post {
        always {
            bat 'docker logout'
        }
    }
}
